.TH MYCAT 1 "September 2025" "Version 1.0" "User Commands"
.SH NAME
mycat \- display contents of a file
.SH SYNOPSIS
.B mycat
[\fIfile\fR]
.SH DESCRIPTION
The
.B mycat
command reads the contents of the given file and prints it to standard output.
If no file is specified, it reads from standard input.
.SH AUTHOR
Talha Bhatti <talhabhatti@example.com>

